name: Generate a test build and push to test-build branch

on:
  push:
    branches:
      - test-dev

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push to Test-Build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean up node_modules and package-lock
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build # The build command of your project
        env:
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }} # Use test server URL for test builds

      - name: Push to test-build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: test-build           # The branch to push the test build to
          FOLDER: dist                 # The directory containing the build output
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Test Build: ({sha}) {msg}" # Custom commit message for test builds
